version: "3.8"

services:
  app:
    container_name: react-app
    image: react-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/react-app/src
    ports:
      - 3000:3000